export const DRIZZLE_ADD_CONTRACTS = 'DRIZZLE_ADD_CONTRACTS';
export const DRIZZLE_INITIALIZED = 'DRIZZLE_INITIALIZED';
export const TX_BROADCASTED = 'TX_BROADCASTED';
export const GOT_CONTRACT_VAR = 'GOT_CONTRACT_VAR';
export const DELETE_CONTRACT = 'DELETE_CONTRACT';
export const ADD_WATCHED_CONTRACTS = 'ADD_WATCHED_CONTRACTS';
export const CONTRACT_INITIALIZED = 'CONTRACT_INITIALIZED';
export const ETH_BALANCE_UPDATED = 'ETH_BALANCE_UPDATED';
