export const VAULTS_LOADED = 'VAULTS_LOADED';
export const USER_VAULT_STATISTICS_LOADED = 'USER_VAULT_STATISTICS_LOADED ';
export const WITHDRAW_FROM_VAULT = 'WITHDRAW_FROM_VAULT';
export const DEPOSIT_TO_VAULT = 'DEPOSIT_TO_VAULT';
export const CLAIM_BACKSCRATCHER_REWARDS = 'CLAIM_BACKSCRATCHER_REWARDS';
