export const INIT_ZAPPER = 'INIT_ZAPPER';
export const ZAPPER_DATA_LOADED = 'ZAPPER_DATA_LOADED';
export const ZAP_IN = 'ZAP_IN';
export const ZAP_OUT_APPROVE = 'ZAP_OUT_APPROVE';
export const ZAP_OUT_WITHDRAW = 'ZAP_OUT_WITHDRAW';
export const ZAP_IN_ERROR = 'ZAP_IN_ERROR';
export const ZAP_OUT_ERROR = 'ZAP_OUT_ERROR';
export const ZAP_OUT_ALLOWANCE = 'ZAP_OUT_ALLOWANCE';
export const MIGRATE_PICKLE_GAUGE = 'MIGRATE_PICKLE_GAUGE';

export const ETH_ADDRESS = '0x0000000000000000000000000000000000000000';
export const DEFAULT_SLIPPAGE = '0.01';
