export const VAULTS_LOADED = 'VAULTS_LOADED';
export const APP_READY = 'APP_READY';
export const APP_INITIALIZED = 'APP_INITIALIZED';

export const DRIZZLE_ADD_CONTRACTS = 'DRIZZLE_ADD_CONTRACTS';

export const ROUTE_CHANGED = 'ROUTE_CHANGED';
export const SPLASH_PAGE_VISITED = 'SPLASH_PAGE_VISITED';
